package com.sw1.umltool.features.diagram.operation;

public enum DiagramOperationType {
    CREATE_CLASS,
    DELETE_CLASS,
    RENAME_CLASS,
    SET_CLASS_ABSTRACT,
    ADD_ATTRIBUTE,
    UPDATE_ATTRIBUTE,
    REMOVE_ATTRIBUTE,
    ADD_METHOD,
    UPDATE_METHOD,
    REMOVE_METHOD,
    ADD_PARAMETER,
    UPDATE_PARAMETER,
    REMOVE_PARAMETER,
    CREATE_RELATION,
    DELETE_RELATION,
    CREATE_ASSOCIATION_CLASS,
    CREATE_ASSOCIATION_CLASS_LINK,
    DELETE_ASSOCIATION_CLASS_LINK,
    CHANGE_RELATION_TYPE,
    CHANGE_MULTIPLICITY,
    CHANGE_RELATION_ROLES,
    CHANGE_NAVIGABILITY,
    MOVE_CLASS,
    RESIZE_CLASS,
    UPDATE_CLASS_STYLE
}
